import { FieldType, FieldCategory, FieldTypeConfig } from "@/types/field-types";

export const FIELD_TYPE_CONFIGS: Record<FieldType, FieldTypeConfig> = {
  // =====================
  // BASIC FIELDS
  // =====================
  short_text: {
    type: "short_text",
    label: "Short Text",
    icon: "Type",
    category: "basic",
    description: "Single line text input",
    hasOptions: false,
    hasValidation: true,
    defaultConfig: {},
    defaultValidation: { max_length: 255 },
  },
  long_text: {
    type: "long_text",
    label: "Long Text",
    icon: "AlignLeft",
    category: "basic",
    description: "Multi-line text area",
    hasOptions: false,
    hasValidation: true,
    defaultConfig: { rows: 4 },
    defaultValidation: { max_length: 5000 },
  },
  number: {
    type: "number",
    label: "Number",
    icon: "Hash",
    category: "basic",
    description: "Numeric input",
    hasOptions: false,
    hasValidation: true,
    defaultConfig: { step: 1 },
    defaultValidation: {},
  },
  email: {
    type: "email",
    label: "Email",
    icon: "Mail",
    category: "basic",
    description: "Email address input",
    hasOptions: false,
    hasValidation: true,
    defaultConfig: {},
    defaultValidation: {},
  },
  phone: {
    type: "phone",
    label: "Phone",
    icon: "Phone",
    category: "basic",
    description: "Phone number input",
    hasOptions: false,
    hasValidation: true,
    defaultConfig: {},
    defaultValidation: {},
  },
  url: {
    type: "url",
    label: "URL",
    icon: "Link",
    category: "basic",
    description: "Website URL input",
    hasOptions: false,
    hasValidation: true,
    defaultConfig: {},
    defaultValidation: {},
  },
  date: {
    type: "date",
    label: "Date",
    icon: "Calendar",
    category: "basic",
    description: "Date picker",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: { date_format: "yyyy-MM-dd" },
    defaultValidation: {},
  },
  time: {
    type: "time",
    label: "Time",
    icon: "Clock",
    category: "basic",
    description: "Time picker",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: { time_format: "24h" },
    defaultValidation: {},
  },
  datetime: {
    type: "datetime",
    label: "Date & Time",
    icon: "CalendarDays",
    category: "basic",
    description: "Combined date and time picker",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  month: {
    type: "month",
    label: "Month",
    icon: "CalendarRange",
    category: "basic",
    description: "Month picker",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  week: {
    type: "week",
    label: "Week",
    icon: "Weekends",
    category: "basic",
    description: "Week picker",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  color: {
    type: "color",
    label: "Color Picker",
    icon: "Palette",
    category: "basic",
    description: "Color selection input",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  password: {
    type: "password",
    label: "Password",
    icon: "Lock",
    category: "basic",
    description: "Password input",
    hasOptions: false,
    hasValidation: true,
    defaultConfig: {},
    defaultValidation: { min_length: 8 },
  },
  search: {
    type: "search",
    label: "Search",
    icon: "Search",
    category: "basic",
    description: "Search input field",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },

  // =====================
  // CHOICE FIELDS
  // =====================
  single_choice: {
    type: "single_choice",
    label: "Single Choice",
    icon: "CircleDot",
    category: "choice",
    description: "Radio button selection",
    hasOptions: true,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  multiple_choice: {
    type: "multiple_choice",
    label: "Multiple Choice",
    icon: "CheckSquare",
    category: "choice",
    description: "Checkbox selection",
    hasOptions: true,
    hasValidation: true,
    defaultConfig: {},
    defaultValidation: {},
  },
  dropdown: {
    type: "dropdown",
    label: "Dropdown",
    icon: "ChevronDown",
    category: "choice",
    description: "Dropdown select",
    hasOptions: true,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  linear_scale: {
    type: "linear_scale",
    label: "Linear Scale",
    icon: "Sliders",
    category: "choice",
    description: "Scale from min to max",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {
      scale_min: 1,
      scale_max: 5,
      scale_min_label: "",
      scale_max_label: "",
    },
    defaultValidation: {},
  },
  rating: {
    type: "rating",
    label: "Rating",
    icon: "Star",
    category: "choice",
    description: "Star rating",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: { rating_max: 5, rating_icon: "star" },
    defaultValidation: {},
  },
  nps: {
    type: "nps",
    label: "NPS Score",
    icon: "Gauge",
    category: "choice",
    description: "Net Promoter Score (0-10)",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: { scale_min: 0, scale_max: 10 },
    defaultValidation: {},
  },
  yes_no: {
    type: "yes_no",
    label: "Yes/No",
    icon: "ToggleLeft",
    category: "choice",
    description: "Toggle switch (yes/no)",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  image_choice: {
    type: "image_choice",
    label: "Image Choice",
    icon: "Image",
    category: "choice",
    description: "Select from images",
    hasOptions: true,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  matrix: {
    type: "matrix",
    label: "Matrix",
    icon: "Grid3x3",
    category: "choice",
    description: "Matrix/grid question",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {
      matrix_rows: [
        { id: "row1", label: "Row 1" },
        { id: "row2", label: "Row 2" },
      ],
      matrix_columns: [
        { id: "col1", label: "Column 1" },
        { id: "col2", label: "Column 2" },
      ],
      matrix_allow_multiple: false,
    },
    defaultValidation: {},
  },

  // =====================
  // ADVANCED FIELDS
  // =====================
  file_upload: {
    type: "file_upload",
    label: "File Upload",
    icon: "Upload",
    category: "advanced",
    description: "File upload field",
    hasOptions: false,
    hasValidation: true,
    defaultConfig: { max_file_size: 5242880, max_files: 1 },
    defaultValidation: {
      max_file_size: 5242880,
      allowed_file_types: ["image/*", "application/pdf"],
    },
  },
  image_upload: {
    type: "image_upload",
    label: "Image Upload",
    icon: "ImagePlus",
    category: "advanced",
    description: "Image upload with preview",
    hasOptions: false,
    hasValidation: true,
    defaultConfig: { max_file_size: 10485760, max_files: 5 },
    defaultValidation: {
      max_file_size: 10485760,
      allowed_file_types: ["image/*"],
    },
  },
  signature: {
    type: "signature",
    label: "Signature",
    icon: "PenTool",
    category: "advanced",
    description: "Signature pad",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  richtext: {
    type: "richtext",
    label: "Rich Text",
    icon: "FileText",
    category: "advanced",
    description: "Rich text editor",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: { rows: 6 },
    defaultValidation: {},
  },
  video_embed: {
    type: "video_embed",
    label: "Video Embed",
    icon: "Video",
    category: "advanced",
    description: "Embed YouTube/Vimeo video",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  google_places: {
    type: "google_places",
    label: "Address (Google Places)",
    icon: "MapPin",
    category: "advanced",
    description: "Address autocomplete",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  calculation: {
    type: "calculation",
    label: "Calculated Field",
    icon: "Calculator",
    category: "advanced",
    description: "Calculate from other fields",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  hidden: {
    type: "hidden",
    label: "Hidden Field",
    icon: "EyeOff",
    category: "advanced",
    description: "Hidden field (internal use)",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  html_snippet: {
    type: "html_snippet",
    label: "HTML Snippet",
    icon: "Code",
    category: "advanced",
    description: "Custom HTML content",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  timer: {
    type: "timer",
    label: "Timer",
    icon: "Timer",
    category: "advanced",
    description: "Countdown timer",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: { duration_seconds: 60 },
    defaultValidation: {},
  },
  consent_checkbox: {
    type: "consent_checkbox",
    label: "Consent / Terms",
    icon: "ShieldCheck",
    category: "verification",
    description: "Consent checkbox with link",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: { consent_text: "I agree to the terms and conditions" },
    defaultValidation: {},
  },

  // =====================
  // LAYOUT FIELDS
  // =====================
  section_header: {
    type: "section_header",
    label: "Section Header",
    icon: "Heading",
    category: "layout",
    description: "Section title and description",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: { header_size: "h2" },
    defaultValidation: {},
  },
  form_header: {
    type: "form_header",
    label: "En-tête du formulaire",
    icon: "LayoutPanelTop",
    category: "layout",
    description: "Personnaliser le titre, la description et l’image/motif de l’en-tête",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {
      header_style: "default",
      header_height: "large",
      header_pattern: "dots",
    },
    defaultValidation: {},
  },
  paragraph_text: {
    type: "paragraph_text",
    label: "Paragraph",
    icon: "AlignLeft",
    category: "layout",
    description: "Display text paragraph",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  divider: {
    type: "divider",
    label: "Divider",
    icon: "Minus",
    category: "layout",
    description: "Horizontal divider line",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  spacer: {
    type: "spacer",
    label: "Spacer",
    icon: "ArrowDown",
    category: "layout",
    description: "Vertical spacing",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: { spacer_size: 24 },
    defaultValidation: {},
  },
  columns_2: {
    type: "columns_2",
    label: "2 Columns",
    icon: "Columns2",
    category: "layout",
    description: "Two column layout",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  columns_3: {
    type: "columns_3",
    label: "3 Columns",
    icon: "Columns3",
    category: "layout",
    description: "Three column layout",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  columns_4: {
    type: "columns_4",
    label: "4 Columns",
    icon: "LayoutGrid",
    category: "layout",
    description: "Four column layout",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  image: {
    type: "image",
    label: "Image",
    icon: "Image",
    category: "media",
    description: "Display an image",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: { image_url: "", image_alt: "" },
    defaultValidation: {},
  },
  video: {
    type: "video",
    label: "Video",
    icon: "Play",
    category: "media",
    description: "Display a video",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: { video_url: "" },
    defaultValidation: {},
  },
  accordion: {
    type: "accordion",
    label: "Accordion",
    icon: "ChevronDown",
    category: "layout",
    description: "Collapsible content section",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: { accordion_title: "", accordion_content: "" },
    defaultValidation: {},
  },
};

export const FIELD_CATEGORIES: { key: FieldCategory; label: string }[] = [
  { key: "basic", label: "Basic" },
  { key: "choice", label: "Choice" },
  { key: "advanced", label: "Advanced" },
  { key: "layout", label: "Layout" },
  { key: "media", label: "Media" },
  { key: "verification", label: "Verification" },
];

export const LAYOUT_FIELD_TYPES: FieldType[] = [
  "section_header",
  "form_header",
  "paragraph_text", 
  "divider", 
  "spacer",
  "columns_2",
  "columns_3", 
  "columns_4",
  "accordion"
];

export function isLayoutField(type: FieldType): boolean {
  return LAYOUT_FIELD_TYPES.includes(type);
}

export function getFieldsByCategory(category: FieldCategory): FieldTypeConfig[] {
  return Object.values(FIELD_TYPE_CONFIGS).filter((f) => f.category === category);
}
