import { FieldType, FieldCategory, FieldTypeConfig } from "@/types/field-types";

export const FIELD_TYPE_CONFIGS: Record<FieldType, FieldTypeConfig> = {
  // =====================
  // BASIC FIELDS
  // =====================
  short_text: {
    type: "short_text",
    label: "Texte court",
    icon: "Type",
    category: "basic",
    description: "Champ texte sur une ligne",
    hasOptions: false,
    hasValidation: true,
    defaultConfig: {},
    defaultValidation: { max_length: 255 },
  },
  long_text: {
    type: "long_text",
    label: "Texte long",
    icon: "AlignLeft",
    category: "basic",
    description: "Zone de texte multi-lignes",
    hasOptions: false,
    hasValidation: true,
    defaultConfig: { rows: 4 },
    defaultValidation: { max_length: 5000 },
  },
  number: {
    type: "number",
    label: "Nombre",
    icon: "Hash",
    category: "basic",
    description: "Champ numérique",
    hasOptions: false,
    hasValidation: true,
    defaultConfig: { step: 1 },
    defaultValidation: {},
  },
  email: {
    type: "email",
    label: "Email",
    icon: "Mail",
    category: "basic",
    description: "Champ adresse email",
    hasOptions: false,
    hasValidation: true,
    defaultConfig: {},
    defaultValidation: {},
  },
  phone: {
    type: "phone",
    label: "Téléphone",
    icon: "Phone",
    category: "basic",
    description: "Numéro de téléphone",
    hasOptions: false,
    hasValidation: true,
    defaultConfig: {},
    defaultValidation: {},
  },
  url: {
    type: "url",
    label: "URL",
    icon: "Link",
    category: "basic",
    description: "Lien vers un site web",
    hasOptions: false,
    hasValidation: true,
    defaultConfig: {},
    defaultValidation: {},
  },
  date: {
    type: "date",
    label: "Date",
    icon: "Calendar",
    category: "basic",
    description: "Sélecteur de date",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: { date_format: "yyyy-MM-dd" },
    defaultValidation: {},
  },
  time: {
    type: "time",
    label: "Heure",
    icon: "Clock",
    category: "basic",
    description: "Sélecteur d'heure",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: { time_format: "24h" },
    defaultValidation: {},
  },
  datetime: {
    type: "datetime",
    label: "Date & Heure",
    icon: "CalendarDays",
    category: "basic",
    description: "Sélecteur combiné date et heure",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  month: {
    type: "month",
    label: "Mois",
    icon: "CalendarRange",
    category: "basic",
    description: "Sélecteur de mois",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  week: {
    type: "week",
    label: "Semaine",
    icon: "Weekends",
    category: "basic",
    description: "Sélecteur de semaine",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  color: {
    type: "color",
    label: "Couleur",
    icon: "Palette",
    category: "basic",
    description: "Sélecteur de couleur",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  password: {
    type: "password",
    label: "Mot de passe",
    icon: "Lock",
    category: "basic",
    description: "Champ mot de passe",
    hasOptions: false,
    hasValidation: true,
    defaultConfig: {},
    defaultValidation: { min_length: 8 },
  },
  search: {
    type: "search",
    label: "Recherche",
    icon: "Search",
    category: "basic",
    description: "Champ de recherche",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },

  // =====================
  // CHOICE FIELDS
  // =====================
  single_choice: {
    type: "single_choice",
    label: "Choix unique",
    icon: "CircleDot",
    category: "choice",
    description: "Sélection par bouton radio",
    hasOptions: true,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  multiple_choice: {
    type: "multiple_choice",
    label: "Choix multiple",
    icon: "CheckSquare",
    category: "choice",
    description: "Sélection par cases à cocher",
    hasOptions: true,
    hasValidation: true,
    defaultConfig: {},
    defaultValidation: {},
  },
  dropdown: {
    type: "dropdown",
    label: "Liste déroulante",
    icon: "ChevronDown",
    category: "choice",
    description: "Sélection dans une liste",
    hasOptions: true,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  linear_scale: {
    type: "linear_scale",
    label: "Échelle linéaire",
    icon: "Sliders",
    category: "choice",
    description: "Échelle de valeurs min à max",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {
      scale_min: 1,
      scale_max: 5,
      scale_min_label: "",
      scale_max_label: "",
    },
    defaultValidation: {},
  },
  rating: {
    type: "rating",
    label: "Notation",
    icon: "Star",
    category: "choice",
    description: "Notation par étoiles",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: { rating_max: 5, rating_icon: "star" },
    defaultValidation: {},
  },
  nps: {
    type: "nps",
    label: "Score NPS",
    icon: "Gauge",
    category: "choice",
    description: "Score de recommandation (0-10)",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: { scale_min: 0, scale_max: 10 },
    defaultValidation: {},
  },
  yes_no: {
    type: "yes_no",
    label: "Oui/Non",
    icon: "ToggleLeft",
    category: "choice",
    description: "Interrupteur oui/non",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  image_choice: {
    type: "image_choice",
    label: "Choix image",
    icon: "Image",
    category: "choice",
    description: "Sélection parmi des images",
    hasOptions: true,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  matrix: {
    type: "matrix",
    label: "Matrice",
    icon: "Grid3x3",
    category: "choice",
    description: "Question en grille/matrice",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {
      matrix_rows: [
        { id: "row1", label: "Ligne 1" },
        { id: "row2", label: "Ligne 2" },
      ],
      matrix_columns: [
        { id: "col1", label: "Colonne 1" },
        { id: "col2", label: "Colonne 2" },
      ],
      matrix_allow_multiple: false,
    },
    defaultValidation: {},
  },

  // =====================
  // ADVANCED FIELDS
  // =====================
  file_upload: {
    type: "file_upload",
    label: "Téléverser fichier",
    icon: "Upload",
    category: "advanced",
    description: "Champ d'envoi de fichier",
    hasOptions: false,
    hasValidation: true,
    defaultConfig: { max_file_size: 5242880, max_files: 1 },
    defaultValidation: {
      max_file_size: 5242880,
      allowed_file_types: ["image/*", "application/pdf"],
    },
  },
  image_upload: {
    type: "image_upload",
    label: "Téléverser image",
    icon: "ImagePlus",
    category: "advanced",
    description: "Envoi d'image avec aperçu",
    hasOptions: false,
    hasValidation: true,
    defaultConfig: { max_file_size: 10485760, max_files: 5 },
    defaultValidation: {
      max_file_size: 10485760,
      allowed_file_types: ["image/*"],
    },
  },
  signature: {
    type: "signature",
    label: "Signature",
    icon: "PenTool",
    category: "advanced",
    description: "Pad de signature",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  richtext: {
    type: "richtext",
    label: "Texte enrichi",
    icon: "FileText",
    category: "advanced",
    description: "Éditeur de texte enrichi",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: { rows: 6 },
    defaultValidation: {},
  },
  video_embed: {
    type: "video_embed",
    label: "Vidéo intégrée",
    icon: "Video",
    category: "advanced",
    description: "Intégrer une vidéo YouTube/Vimeo",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  google_places: {
    type: "google_places",
    label: "Adresse (Google Places)",
    icon: "MapPin",
    category: "advanced",
    description: "Adresse avec auto-complétion",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  calculation: {
    type: "calculation",
    label: "Champ calculé",
    icon: "Calculator",
    category: "advanced",
    description: "Calcul à partir d'autres champs",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  hidden: {
    type: "hidden",
    label: "Champ masqué",
    icon: "EyeOff",
    category: "advanced",
    description: "Champ caché (usage interne)",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  html_snippet: {
    type: "html_snippet",
    label: "Bloc HTML",
    icon: "Code",
    category: "advanced",
    description: "Contenu HTML personnalisé",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  timer: {
    type: "timer",
    label: "Minuteur",
    icon: "Timer",
    category: "advanced",
    description: "Compte à rebours",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: { duration_seconds: 60 },
    defaultValidation: {},
  },
  consent_checkbox: {
    type: "consent_checkbox",
    label: "Consentement",
    icon: "ShieldCheck",
    category: "verification",
    description: "Case de consentement avec lien",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: { consent_text: "J'accepte les conditions générales" },
    defaultValidation: {},
  },

  // =====================
  // LAYOUT FIELDS
  // =====================
  section_header: {
    type: "section_header",
    label: "En-tête de section",
    icon: "Heading",
    category: "layout",
    description: "Titre et description de section",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: { header_size: "h2" },
    defaultValidation: {},
  },
  form_header: {
    type: "form_header",
    label: "En-tête du formulaire",
    icon: "LayoutPanelTop",
    category: "layout",
    description: "Personnaliser le titre, la description et l’image/motif de l’en-tête",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {
      header_style: "default",
      header_height: "large",
      header_pattern: "dots",
    },
    defaultValidation: {},
  },
  paragraph_text: {
    type: "paragraph_text",
    label: "Paragraphe",
    icon: "AlignLeft",
    category: "layout",
    description: "Afficher un paragraphe de texte",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  divider: {
    type: "divider",
    label: "Séparateur",
    icon: "Minus",
    category: "layout",
    description: "Ligne de séparation horizontale",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  spacer: {
    type: "spacer",
    label: "Espacement",
    icon: "ArrowDown",
    category: "layout",
    description: "Espace vertical",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: { spacer_size: 24 },
    defaultValidation: {},
  },
  columns_2: {
    type: "columns_2",
    label: "2 Colonnes",
    icon: "Columns2",
    category: "layout",
    description: "Disposition en deux colonnes",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  columns_3: {
    type: "columns_3",
    label: "3 Colonnes",
    icon: "Columns3",
    category: "layout",
    description: "Disposition en trois colonnes",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  columns_4: {
    type: "columns_4",
    label: "4 Colonnes",
    icon: "LayoutGrid",
    category: "layout",
    description: "Disposition en quatre colonnes",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: {},
    defaultValidation: {},
  },
  image: {
    type: "image",
    label: "Image",
    icon: "Image",
    category: "media",
    description: "Afficher une image",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: { image_url: "", image_alt: "" },
    defaultValidation: {},
  },
  video: {
    type: "video",
    label: "Vidéo",
    icon: "Play",
    category: "media",
    description: "Afficher une vidéo",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: { video_url: "" },
    defaultValidation: {},
  },
  accordion: {
    type: "accordion",
    label: "Accordéon",
    icon: "ChevronDown",
    category: "layout",
    description: "Section de contenu pliable",
    hasOptions: false,
    hasValidation: false,
    defaultConfig: { accordion_title: "", accordion_content: "" },
    defaultValidation: {},
  },
};

export const FIELD_CATEGORIES: { key: FieldCategory; label: string }[] = [
  { key: "basic", label: "Basique" },
  { key: "choice", label: "Choix" },
  { key: "advanced", label: "Avancé" },
  { key: "layout", label: "Mise en page" },
  { key: "media", label: "Média" },
  { key: "verification", label: "Vérification" },
];

export const LAYOUT_FIELD_TYPES: FieldType[] = [
  "section_header",
  "form_header",
  "paragraph_text", 
  "divider", 
  "spacer",
  "columns_2",
  "columns_3", 
  "columns_4",
  "accordion"
];

export function isLayoutField(type: FieldType): boolean {
  return LAYOUT_FIELD_TYPES.includes(type);
}

export function getFieldsByCategory(category: FieldCategory): FieldTypeConfig[] {
  return Object.values(FIELD_TYPE_CONFIGS).filter((f) => f.category === category);
}
